### ISSUE TITLE
扫码卡住无法完成后续安装

### ISSUE THREAD

**Issue by qwerrsc** [soloxiaoye2022/zhenxun_bot-deploy#2]
建议增加密码登陆，服务器安装是无法扫码，而卡住无法完成后续安装

**Comment by BMC-Gordon0921** [comment]
开新终端，输入命令以后切换到gocqhttp菜单，查看gocq日志以后再去扫码或者拉条验证（不过推荐扫码）

**Comment by soloxiaoye2022** [comment]
收到，已新增密码登陆选项。

**Comment by soloxiaoye2022** [comment]
> 建议增加密码登陆，服务器安装是无法扫码，而卡住无法完成后续安装

收到，已新增密码登陆选项。
